name: Build and deploy V10

on:
  workflow_call:
    inputs:
      run_number:
        required: true
        type: string
      build_platform:
        required: true
        type: string
      build_configuration:
        required: true
        type: string
      environment_name:
        required: true
        type: string
    secrets:
      solution_name:
        required: true
      website_name:
        required: true
      server_name:
        required: true
      username:
        required: true
      password:
        required: true
      keyvaulttenantid:
        required: true
      keyvaultclientid:
        required: true
      keyvaultclientsecret:
        required: true

env:
    SolutionName: ${{ secrets.solution_name }}
    BuildPlatform: ${{ inputs.build_platform }}
    BuildConfiguration: ${{ inputs.build_configuration }}
    EnvironmentName: ${{ inputs.environment_name }}

jobs:
  run-forest-run:
  
    runs-on: self-hosted
    
    steps:
        - name: Get current date
          id: date
          uses: Kaven-Universe/github-action-current-date-time@v1.2.0
          with:
            format: "YYYY_MM_DD HH_mm_ss_SSS"

        - name: Checkout
          uses: actions/checkout@v3
      
        - name: Create Build Directory
          run: mkdir _build
      
        - name: Replace variables
          uses: microsoft/variable-substitution@v1 
          with:
            files: 'Ph.Umbraco.Web/appsettings.Production.json'
          env:
            Umbraco.CMS.RuntimeMinification.Version: ${{ github.run_id }}
      
        - name: Replace Key Vault
          uses: cschleiden/replace-tokens@v1
          with:
            files: '["Ph.Umbraco.Web/web.config"]'
          env:
            UpdateAzureTenantId: ${{ secrets.keyvaulttenantid }}
            UpdateAzureClientId: ${{ secrets.keyvaultclientid }}
            UpdateAzureClientSecret: ${{ secrets.keyvaultclientsecret }}

        - name: Build Solution
          run: | 
            dotnet build ${{env.SolutionName}} /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:DeleteExistingFiles=True /p:SkipInvalidConfigurations=true /p:IncludeSetAclProviderOnDestination=False /p:AutoParameterizationWebConfigConnectionStrings=False /p:platform="${{env.BuildPlatform}}" /p:configuration="${{env.BuildConfiguration}}" /p:PackageLocation="../_build" /p:EnvironmentName=${{env.EnvironmentName}} --no-self-contained -p:MyRuntimeIdentifier=win-x64        

        - name: Deploy to Server
          uses: PhCreative/.github/.github/actions/ph-web-deploy-v10@master
          with:
            website-name: ${{ secrets.website_name }}
            server-computer-name: ${{ secrets.server_name }}
            server-username: ${{ secrets.username }}
            server-password: ${{ secrets.password }}
            source-path: '_build'
            source-fileName: 'Ph.Umbraco.Web.zip'
            
        - name: Tag Build
          uses: PhCreative/.github/.github/actions/github-tagger@master
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{env.EnvironmentName}}Build-${{ steps.date.outputs.year }}${{ steps.date.outputs.month }}${{ steps.date.outputs.day }}-${{ inputs.run_number }}
        
        - name: Clean up after run
          uses: mickem/clean-after-action@v2
