name: Build and deploy V10

on:
  workflow_call:
    inputs:
      run_number:
        required: true
        type: string
      build_platform:
        required: true
        type: string
      build_configuration:
        required: true
        type: string
    secrets:
      solution_name:
        required: true
      website_name:
        required: true
      server_name:
        required: true
      username:
        required: true
      password:
        required: true

env:
    SolutionName: ${{ secrets.solution_name }}
    BuildPlatform: ${{ inputs.build_platform }}
    BuildConfiguration: ${{ inputs.build_configuration }}

jobs:
  run-forest-run:
  
    runs-on: self-hosted
    
    steps:
        - name: Get current date
          id: date
          uses: Kaven-Universe/github-action-current-date-time@v1.2.0
          with:
            format: "YYYY_MM_DD HH_mm_ss_SSS"

        - name: Checkout
          uses: actions/checkout@v3
      
        - name: Create Build Directory
          run: mkdir _build
      
        - name: Build Solution
          run: | 
            dotnet build ${{env.SolutionName}} /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:DeleteExistingFiles=True /p:SkipInvalidConfigurations=true /p:IncludeSetAclProviderOnDestination=False /p:AutoParameterizationWebConfigConnectionStrings=False /p:platform="${{env.BuildPlatform}}" /p:configuration="${{env.BuildConfiguration}}" /p:PackageLocation="../_build"
        
        - name: Deploy to Server
          uses: PhCreative/.github/.github/actions/ph-web-deploy-test@master
          with:
            website-name: ${{ secrets.website_name }}
            server-computer-name: ${{ secrets.server_name }}
            server-username: ${{ secrets.username }}
            server-password: ${{ secrets.password }}
            source-path: '_build'
            source-fileName: 'Ph.Umbraco.Web.zip'
            
        - name: Tag Build
          uses: PhCreative/.github/.github/actions/github-tagger@master
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            tag: UATBuild-${{ steps.date.outputs.year }}${{ steps.date.outputs.month }}${{ steps.date.outputs.day }}-${{ inputs.run_number }}
        
        - name: Clean up after run
          uses: mickem/clean-after-action@v2
